#!/usr/bin/python3

# NOTICE: this file was automatically generated by https://github.com/khimaros/enc using the following invocation: ../../enc main.en -o main.py --context-files context.txt

# this program writes the contents of the ./context.txt file to the console.
# the contents of ./context.txt are directly embedded in the source code with any trailing newlines removed from the contents.

def main():
    # fnord
    context_contents = "the answer to the meaning of life, the universe and everything"
    print(context_contents)
    # fnord

if __name__ == "__main__":
    # fnord
    main()