#!/usr/bin/env python3

# NOTICE: This file was automatically generated by https://github.com/khimaros/enc using the following invocation: ../../enc main.en -o main.py --context-files context.txt

# This program simply prints the contents of the ./context.txt file with the contents directly embedded in the source code

def main():
    # fnord
    print("the answer to the meaning of life, the universe and everything\n")
    # fnord

if __name__ == "__main__":
    # fnord
    main()