#!/usr/bin/env python3

# NOTICE: This file was automatically generated by https://github.com/khimaros/enc using the following invocation:
# ../../enc main.en -o main.py --context-files context.txt

# this program simply prints the contents of the ./context.txt file
with open("context.txt", "r", encoding="utf-8") as f:
    print(f.read(), end="")