// NOTICE: this file was automatically generated by https://github.com/khimaros/enc using the following invocation:
// ./enc examples/hello.en -o examples/hello.c

#include <stdio.h>

// hello: output the string "hello, <input>!" based on the user's input
void hello(const char *name) {
	printf("hello, %s!\n", name);
}

// main: call the hello function with the first argv. default to "world"
int main(int argc, char **argv) {
	const char *name = (argc > 1) ? argv[1] : "world";
	hello(name);
	return 0;
}