// NOTICE: This file was automatically generated by https://github.com/khimaros/enc using the following invocation: ./enc examples/hello.en -o examples/hello.c
#include <stdio.h>

// hello: output the string "hello, <input>!" based on the user's input
void
hello(const char *input)
{
	printf("hello, %s!\n", input);
}

// main: call the hello function with the first argv. default to "world"
int
main(int argc, char *argv[])
{
	if (argc > 1) {
		hello(argv[1]);
	} else {
		hello("world");
	}
	return 0;
}