#!/usr/bin/env python3
# NOTICE: this file was automatically generated by https://github.com/khimaros/enc using the following invocation:
# enc lib.en -o lib.py

import tkinter as tk
from tkinter import simpledialog
from tkinter import messagebox

# this is the main library which exposes a few functions to main

# prompt: a function that reads a single number from the user using a graphical dialog
def prompt():
    root = tk.Tk()
    root.withdraw()
    # askinteger returns an int or None if the dialog is cancelled
    number = simpledialog.askinteger("Input", "Please enter a number:", parent=root)
    root.destroy()
    return number

# add: a function that adds two numbers
def add(a, b):
    return a + b

# display: a function that creates a graphical dialog and displays any text provided
def display(text):
    root = tk.Tk()
    root.withdraw()
    messagebox.showinfo("Display", str(text), parent=root)
    root.destroy()