#!/usr/bin/env python3
# NOTICE: This file was automatically generated by https://github.com/khimaros/enc using the following invocation:
# enc lib.en -o lib.py

import tkinter
from tkinter import simpledialog, messagebox

# Set up the root Tkinter window and hide it
# This is necessary for the dialogs to work correctly without a main window
_root = tkinter.Tk()
_root.withdraw()

# prompt: a function that reads a single number from the user using a graphical dialog
def prompt():
    """
    Prompts the user for a single integer using a graphical dialog.
    Returns the integer entered by the user, or None if the dialog is cancelled.
    """
    return simpledialog.askinteger("Input", "Please enter a number:")

# add: a function that adds two numbers
def add(a, b):
    """
    Adds two numbers and returns the result.
    """
    return a + b

# display: a function that creates a graphical dialog and displays any text provided
def display(text):
    """
    Displays the provided text in a graphical information dialog.
    """
    messagebox.showinfo("Display", text)