#!/usr/bin/env python3
# NOTICE: this file was automatically generated by https://github.com/khimaros/enc using the following invocation: enc main.en -o main.py --context-files lib.py

# this is the main business logic, it primarly calls functions defined in lib
import lib

# it uses the prompt() function to read two numbers
num1 = lib.prompt()
num2 = lib.prompt()

# We should only proceed if the user actually entered two numbers.
# The prompt() function returns None if the user cancels the dialog.
if num1 is not None and num2 is not None:
    # calls the add() with those numbers,
    result = lib.add(num1, num2)

    # and finally displays the result using the display() function
    lib.display(result)