#!/usr/bin/env python3
# NOTICE: This file was automatically generated by https://github.com/khimaros/enc using the following invocation:
# enc main.en -o main.py --context-files lib.py

import lib

# this is the main business logic, it primarly calls functions defined in lib
def main():
    # it uses the prompt() function to read two numbers
    num1 = lib.prompt()
    if num1 is None:
        return # User cancelled

    num2 = lib.prompt()
    if num2 is None:
        return # User cancelled

    # calls the add() with those numbers,
    result = lib.add(num1, num2)

    # and finally displays the result using the display() function
    lib.display(f"The result is: {result}")

if __name__ == "__main__":
    main()