#!/usr/bin/env python3
# NOTICE: This file was automatically generated by https://github.com/khimaros/enc using the following invocation: enc main.en -o main.py
import sys

def main():
    """
    Main entry point for the script.
    """
    # a program that produces fibonacci sequence from argv
    if len(sys.argv) != 2:
        print(f"Usage: {sys.argv[0]} <number_of_elements>", file=sys.stderr)
        sys.exit(1)

    try:
        n = int(sys.argv[1])
        if n < 0:
            raise ValueError("Number must be non-negative.")
    except ValueError as e:
        print(f"Error: Invalid input. Please provide a non-negative integer. ({e})", file=sys.stderr)
        sys.exit(1)

    a, b = 0, 1
    for _ in range(n):
        print(a)
        a, b = b, a + b

if __name__ == "__main__":
    main()