// NOTICE: This file was automatically generated by https://github.com/khimaros/enc using the following invocation: enc main.py -o main.c
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <errno.h>

/**
 * // def main():
 * Main entry point for the script.
 */
int main(int argc, char *argv[]) {
    // a program that produces fibonacci sequence from argv
    // if len(sys.argv) != 2:
    if (argc != 2) {
        fprintf(stderr, "Usage: %s <number_of_elements>\n", argv[0]);
        exit(1);
    }

    // try:
    char *endptr;
    errno = 0; // To distinguish success/failure after call
    long n = strtol(argv[1], &endptr, 10);

    if (errno == ERANGE || endptr == argv[1] || *endptr != '\0') {
        // except ValueError as e:
        fprintf(stderr, "Error: Invalid input. Please provide a non-negative integer. (Invalid characters or out of range)\n");
        exit(1);
    }

    // if n < 0:
    if (n < 0) {
        // raise ValueError("Number must be non-negative.")
        fprintf(stderr, "Error: Invalid input. Please provide a non-negative integer. (Number must be non-negative.)\n");
        exit(1);
    }

    // a, b = 0, 1
    unsigned long long a = 0, b = 1;
    // for _ in range(n):
    for (long i = 0; i < n; i++) {
        // print(a)
        printf("%llu\n", a);
        // a, b = b, a + b
        unsigned long long temp = a;
        a = b;
        b = temp + b;
    }

    return 0;
}